using ControlAcceso.BLL;
using Jalogycs.Helpers;
using Logistica.BLL;
using Personas.BLL;
using Utilidades.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using System.Web.SessionState;

namespace Jalogycs
{
    public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            AplicationCtrl.TiposDocumento = PersonaBLL.CargarTipoDocumento();
            AplicationCtrl.Paises = PaisBLL.CargarPaises();
            AplicationCtrl.Ciudades = CiudadBLL.ObtenerCiudades();
            AplicationCtrl.Puertos = PuertoBLL.ObtenerPuertos();
            AplicationCtrl.Puertos = PuertoBLL.ObtenerPuertos();
            AplicationCtrl.Exportador = ClienteBLL.ObtenerExportador();
            AplicationCtrl.Importador = ClienteBLL.ObtenerImportador();
            //AplicationCtrl.Incoterm = IncotermBLL.ObtenerIncoterm();
            AplicationCtrl.TipoOperacion = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoOperacion), null);
            AplicationCtrl.TipoCarga = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoCarga), null);
            AplicationCtrl.Modalidad = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.Modalidad), null);
            AplicationCtrl.ModoTransporte = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.ModoTransporte), null);
            AplicationCtrl.Incoterm = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.Incoterm), null);
            AplicationCtrl.TipoProveedor = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoProveedor), null);
            AplicationCtrl.RazonSocial = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.RazonSocial), null);
            AplicationCtrl.Item = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.Item), null);
            AplicationCtrl.Caracteristicasmercancia = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.Caracteristicasmercancia), null);
            AplicationCtrl.RubroCotizacion = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.RubroCotizacion), null);
            AplicationCtrl.TipoMercancia = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoMercancia), null);
            AplicationCtrl.TipoContenedor = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoContenedor), null);
            AplicationCtrl.Moneda = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.Moneda), null);
            AplicationCtrl.TrayectoAsegurado = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TrayectoAsegurado), null);
            AplicationCtrl.ItemMensajeria = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.ItemMensajeria), null);
            AplicationCtrl.RateClassCode = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.RateClassCode), null);
            AplicationCtrl.FactorEstiba = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.FactorEstiba), null);
            AplicationCtrl.UndmedidaDistancia = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.UndmedidaDistancia), null);
            AplicationCtrl.UndmedidaVolumen = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.UndmedidaVolumen), null);
            AplicationCtrl.UndmedidaPeso = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.UndmedidaPeso), null);
            AplicationCtrl.TipoEmbalaje = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoEmbalaje), null);
            AplicationCtrl.LugarBodega = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.LugarBodega), null);
            AplicationCtrl.TipoDocumento= DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoDocumento), null);
            AplicationCtrl.UN= DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.UN), null);
            AplicationCtrl.TipoDocumentoArchivo = DominioBLL.ObtenerDominioPorTipoDominio(Convert.ToInt64(Utilidades.Entidades.Enumeraciones.TipoDominio.TipoDocumentoArchivo), null);
            AplicationCtrl.Matriz = new List<dynamic>() { new { idorigen=1, iddestino=1,tipo=1 },
                                                          new { idorigen=1, iddestino=2,tipo=1 },
                                                          new { idorigen=2, iddestino=3,tipo=1 },
                                                          new { idorigen=2, iddestino=4,tipo=1 },
                                                          new { idorigen=1, iddestino=1,tipo=2 },
                                                          new { idorigen=1, iddestino=3,tipo=2 },
                                                          new { idorigen=2, iddestino=2,tipo=2 },
                                                          new { idorigen=2, iddestino=3,tipo=2 },
                                                          new { idorigen=3, iddestino=1,tipo=2 },
                                                          new { idorigen=3, iddestino=2,tipo=2 },
                                                          new { idorigen=3, iddestino=3,tipo=2 },
                                                          new { idorigen=4, iddestino=1,tipo=2 },
                                                          new { idorigen=4, iddestino=2,tipo=2 },
                                                          new { idorigen=4, iddestino=3,tipo=2 },
                                                          new { idorigen=5, iddestino=1,tipo=2 },
                                                          new { idorigen=5, iddestino=2,tipo=2 },
                                                          new { idorigen=5, iddestino=3,tipo=2 },
                                                          new { idorigen=6, iddestino=1,tipo=2 },
                                                          new { idorigen=6, iddestino=2,tipo=2 },
                                                          new { idorigen=6, iddestino=3,tipo=2 },


                                                          new { idorigen=1, iddestino=1,tipo=3 },
                                                          new { idorigen=2, iddestino=3,tipo=3 },
                                                          new { idorigen=4, iddestino=1,tipo=3 },
                                                          new { idorigen=4, iddestino=2,tipo=3 },
                                                          new { idorigen=4, iddestino=3,tipo=3 },
                                                          new { idorigen=4, iddestino=4,tipo=3 },
                                                          new { idorigen=4, iddestino=5,tipo=3 },
                                                          new { idorigen=4, iddestino=6,tipo=3 },
                                                          new { idorigen=4, iddestino=7,tipo=3 },
                                                          new { idorigen=4, iddestino=8,tipo=3 },
                                                          new { idorigen=4, iddestino=9,tipo=3 },
                                                          new { idorigen=5, iddestino=2,tipo=3 },
                                                          new { idorigen=5, iddestino=4,tipo=3 },
                                                          new { idorigen=5, iddestino=5,tipo=3 },
                                                          new { idorigen=7, iddestino=1,tipo=3 },
                                                          new { idorigen=7, iddestino=2,tipo=3 },
                                                          new { idorigen=7, iddestino=3,tipo=3 },
                                                          new { idorigen=7, iddestino=4,tipo=3 },
                                                          new { idorigen=7, iddestino=5,tipo=3 },
                                                          new { idorigen=7, iddestino=6,tipo=3 },
                                                          new { idorigen=7, iddestino=7,tipo=3 },
                                                          new { idorigen=7, iddestino=8,tipo=3 },
                                                          new { idorigen=7, iddestino=9,tipo=3 },
                                                          new { idorigen=8, iddestino=6,tipo=3 },
                                                          new { idorigen=9, iddestino=1,tipo=3 },
                                                          new { idorigen=9, iddestino=2,tipo=3 },
                                                          new { idorigen=9, iddestino=3,tipo=3 },
                                                          new { idorigen=9, iddestino=4,tipo=3 },
                                                          new { idorigen=9, iddestino=5,tipo=3 },
                                                          new { idorigen=9, iddestino=6,tipo=3 },
                                                          new { idorigen=9, iddestino=7,tipo=3 },
                                                          new { idorigen=9, iddestino=8,tipo=3 },
                                                          new { idorigen=9, iddestino=9,tipo=3 },
                                                          new { idorigen=10, iddestino=5,tipo=3 },

                                                          new { idorigen=1, iddestino=1,tipo=4 },
                                                          new { idorigen=1, iddestino=2,tipo=4 },
                                                          new { idorigen=2, iddestino=1,tipo=4 }, 
                                                          new { idorigen=2, iddestino=2,tipo=4 },
                                                          new { idorigen=4, iddestino=1,tipo=4 },
                                                          new { idorigen=4, iddestino=2,tipo=4 },
                                                          new { idorigen=4, iddestino=3,tipo=4 },
                                                          new { idorigen=5, iddestino=1,tipo=4 },
                                                          new { idorigen=5, iddestino=2,tipo=4 },
                                                          new { idorigen=5, iddestino=3,tipo=4 },
                                                          new { idorigen=6, iddestino=1,tipo=4 },
                                                          new { idorigen=6, iddestino=2,tipo=4 },
                                                          new { idorigen=6, iddestino=3,tipo=4 },
                                                          new { idorigen=7, iddestino=1,tipo=4 },
                                                          new { idorigen=7, iddestino=2,tipo=4 },
                                                          new { idorigen=7, iddestino=3,tipo=4 },
                                                          new { idorigen=8, iddestino=1,tipo=4 },
                                                          new { idorigen=8, iddestino=2,tipo=4 },
                                                          new { idorigen=8, iddestino=3,tipo=4 },
                                                          new { idorigen=9, iddestino=1,tipo=4 },
                                                          new { idorigen=9, iddestino=2,tipo=4 },
                                                          new { idorigen=9, iddestino=3,tipo=4 },
                                                          new { idorigen=10, iddestino=1,tipo=4 },
                                                          new { idorigen=10, iddestino=2,tipo=4 },

                                                          new { idorigen=1, iddestino=1,tipo=6 },
                                                          new { idorigen=1, iddestino=2,tipo=6 },
                                                          new { idorigen=1, iddestino=3,tipo=6 },
                                                          new { idorigen=1, iddestino=4,tipo=6 },
                                                          new { idorigen=1, iddestino=5,tipo=6 },
                                                          new { idorigen=1, iddestino=6,tipo=6 },
                                                          new { idorigen=2, iddestino=1,tipo=6 },
                                                          new { idorigen=2, iddestino=3,tipo=6 },
                                                          new { idorigen=2, iddestino=4,tipo=6 },
                                                          new { idorigen=2, iddestino=5,tipo=6 },
                                                          new { idorigen=2, iddestino=6,tipo=6 },
                                                          new { idorigen=4, iddestino=1,tipo=6 },
                                                          new { idorigen=4, iddestino=2,tipo=6 },
                                                          new { idorigen=4, iddestino=3,tipo=6 },
                                                          new { idorigen=4, iddestino=4,tipo=6 },
                                                          new { idorigen=4, iddestino=5,tipo=6 },
                                                          new { idorigen=4, iddestino=6,tipo=6 },
                                                          new { idorigen=5, iddestino=1,tipo=6 },
                                                          new { idorigen=5, iddestino=2,tipo=6 },
                                                          new { idorigen=5, iddestino=3,tipo=6 },
                                                          new { idorigen=5, iddestino=4,tipo=6 },
                                                          new { idorigen=5, iddestino=5,tipo=6 },
                                                          new { idorigen=5, iddestino=6,tipo=6 },
                                                          new { idorigen=6, iddestino=1,tipo=6 },
                                                          new { idorigen=6, iddestino=2,tipo=6 },
                                                          new { idorigen=6, iddestino=3,tipo=6 },
                                                          new { idorigen=6, iddestino=4,tipo=6 },
                                                          new { idorigen=6, iddestino=5,tipo=6 },
                                                          new { idorigen=6, iddestino=6,tipo=6 },
                                                          new { idorigen=7, iddestino=1,tipo=6 },
                                                          new { idorigen=7, iddestino=2,tipo=6 },
                                                          new { idorigen=7, iddestino=3,tipo=6 },
                                                          new { idorigen=7, iddestino=4,tipo=6 },
                                                          new { idorigen=7, iddestino=5,tipo=6 },
                                                          new { idorigen=7, iddestino=6,tipo=6 },
                                                          new { idorigen=8, iddestino=1,tipo=6 },
                                                          new { idorigen=9, iddestino=1,tipo=6 },
                                                          new { idorigen=9, iddestino=2,tipo=6 },
                                                          new { idorigen=9, iddestino=3,tipo=6 },
                                                          new { idorigen=9, iddestino=4,tipo=6 },
                                                          new { idorigen=9, iddestino=5,tipo=6 },
                                                          new { idorigen=9, iddestino=6,tipo=6 },
                                                          new { idorigen=10, iddestino=1,tipo=6 },
                                                          new { idorigen=10, iddestino=2,tipo=6 },
                                                          new { idorigen=10, iddestino=3,tipo=6 },
                                                          new { idorigen=10, iddestino=4,tipo=6 },
                                                          new { idorigen=10, iddestino=5,tipo=6 },
                                                          new { idorigen=10, iddestino=6,tipo=6 },

                                                          new { idorigen=1, iddestino=1,tipo=8 },
                                                          new { idorigen=1, iddestino=2,tipo=8 },
                                                          new { idorigen=1, iddestino=3,tipo=8 },
                                                          new { idorigen=1, iddestino=4,tipo=8 },
                                                          new { idorigen=1, iddestino=5,tipo=8 },
                                                          new { idorigen=1, iddestino=6,tipo=8 },
                                                          new { idorigen=2, iddestino=1,tipo=8 },
                                                          new { idorigen=2, iddestino=2,tipo=8 },
                                                          new { idorigen=2, iddestino=3,tipo=8 },
                                                          new { idorigen=2, iddestino=4,tipo=8 },
                                                          new { idorigen=2, iddestino=5,tipo=8 },
                                                          new { idorigen=2, iddestino=6,tipo=8 },
                                                          new { idorigen=3, iddestino=1,tipo=8 },
                                                          new { idorigen=3, iddestino=3,tipo=8 },
                                                          new { idorigen=3, iddestino=4,tipo=8 },
                                                          new { idorigen=3, iddestino=5,tipo=8 },
                                                          new { idorigen=3, iddestino=6,tipo=8 },
                                                          new { idorigen=4, iddestino=1,tipo=8 },
                                                          new { idorigen=4, iddestino=2,tipo=8 },
                                                          new { idorigen=4, iddestino=3,tipo=8 },
                                                          new { idorigen=4, iddestino=4,tipo=8 },
                                                          new { idorigen=4, iddestino=5,tipo=8 },
                                                          new { idorigen=4, iddestino=6,tipo=8 },
                                                          new { idorigen=5, iddestino=1,tipo=8 },
                                                          new { idorigen=5, iddestino=2,tipo=8 },
                                                          new { idorigen=5, iddestino=3,tipo=8 },
                                                          new { idorigen=5, iddestino=4,tipo=8 },
                                                          new { idorigen=5, iddestino=5,tipo=8 },
                                                          new { idorigen=5, iddestino=6,tipo=8 },
                                                          new { idorigen=6, iddestino=1,tipo=8 },                                                          
                                                          new { idorigen=7, iddestino=1,tipo=8 },
                                                          new { idorigen=7, iddestino=2,tipo=8 },
                                                          new { idorigen=7, iddestino=3,tipo=8 },
                                                          new { idorigen=7, iddestino=4,tipo=8 },
                                                          new { idorigen=7, iddestino=5,tipo=8 },
                                                          new { idorigen=7, iddestino=6,tipo=8 },
                                                          new { idorigen=8, iddestino=1,tipo=8 },
                                                          new { idorigen=8, iddestino=2,tipo=8 },
                                                          new { idorigen=8, iddestino=3,tipo=8 },
                                                          new { idorigen=8, iddestino=4,tipo=8 },
                                                          new { idorigen=8, iddestino=5,tipo=8 },
                                                          new { idorigen=8, iddestino=6,tipo=8 },
                                                          new { idorigen=9, iddestino=1,tipo=8 },
                                                          new { idorigen=9, iddestino=2,tipo=8 },
                                                          new { idorigen=9, iddestino=3,tipo=8 },
                                                          new { idorigen=9, iddestino=4,tipo=8 },
                                                          new { idorigen=9, iddestino=5,tipo=8 },
                                                          new { idorigen=9, iddestino=6,tipo=8 },
                                                          new { idorigen=1, iddestino=1,tipo=7 },
                                                          new { idorigen=2, iddestino=1,tipo=7 },
                                                          new { idorigen=3, iddestino=0,tipo=7 },
                                                          new { idorigen=4, iddestino=1,tipo=7 },
                                                          new { idorigen=5, iddestino=1,tipo=7 },
                                                          new { idorigen=6, iddestino=0,tipo=7 },
                                                          new { idorigen=7, iddestino=1,tipo=7 },
                                                          new { idorigen=8, iddestino=1,tipo=7 },
                                                          new { idorigen=9, iddestino=1,tipo=7 },
                                                          new { idorigen=10, iddestino=1,tipo=7 },
                                                          new { idorigen=1, iddestino=1,tipo=9 },
                                                          new { idorigen=1, iddestino=2,tipo=9 },
                                                          new { idorigen=1, iddestino=3,tipo=9 },
                                                          new { idorigen=1, iddestino=4,tipo=9 },
                                                          new { idorigen=1, iddestino=5,tipo=9 },
                                                          new { idorigen=1, iddestino=6,tipo=9 },
                                                          new { idorigen=1, iddestino=7,tipo=9 },
                                                          new { idorigen=1, iddestino=8,tipo=9 },
                                                          new { idorigen=1, iddestino=9,tipo=9 },
                                                          new { idorigen=1, iddestino=10,tipo=9 },
                                                          new { idorigen=1, iddestino=11,tipo=9 },
                                                          new { idorigen=2, iddestino=1,tipo=9 },
                                                          new { idorigen=2, iddestino=2,tipo=9 },
                                                          new { idorigen=2, iddestino=3,tipo=9 },
                                                          new { idorigen=2, iddestino=4,tipo=9 },
                                                          new { idorigen=2, iddestino=5,tipo=9 },
                                                          new { idorigen=2, iddestino=6,tipo=9 },
                                                          new { idorigen=2, iddestino=7,tipo=9 },
                                                          new { idorigen=3, iddestino=1,tipo=9 },
                                                          new { idorigen=3, iddestino=2,tipo=9 },
                                                          new { idorigen=3, iddestino=3,tipo=9 },
                                                          new { idorigen=3, iddestino=4,tipo=9 },
                                                          new { idorigen=3, iddestino=5,tipo=9 },
                                                          new { idorigen=3, iddestino=6,tipo=9 },
                                                          new { idorigen=3, iddestino=7,tipo=9 },
                                                          new { idorigen=4, iddestino=1,tipo=9 },
                                                          new { idorigen=4, iddestino=2,tipo=9 },
                                                          new { idorigen=4, iddestino=3,tipo=9 },
                                                          new { idorigen=4, iddestino=4,tipo=9 },
                                                          new { idorigen=4, iddestino=5,tipo=9 },
                                                          new { idorigen=4, iddestino=6,tipo=9 },
                                                          new { idorigen=4, iddestino=7,tipo=9 },
                                                          new { idorigen=5, iddestino=1,tipo=9 },
                                                          new { idorigen=5, iddestino=2,tipo=9 },
                                                          new { idorigen=5, iddestino=3,tipo=9 },
                                                          new { idorigen=5, iddestino=4,tipo=9 },
                                                          new { idorigen=5, iddestino=5,tipo=9 },
                                                          new { idorigen=5, iddestino=6,tipo=9 },
                                                          new { idorigen=5, iddestino=7,tipo=9 },
                                                          
                                                          new { idorigen=6, iddestino=1,tipo=9 },
                                                          new { idorigen=6, iddestino=2,tipo=9 },
                                                          new { idorigen=6, iddestino=3,tipo=9 },
                                                          new { idorigen=6, iddestino=4,tipo=9 },
                                                          new { idorigen=6, iddestino=5,tipo=9 },
                                                          new { idorigen=6, iddestino=6,tipo=9 },
                                                          new { idorigen=6, iddestino=7,tipo=9 },
                                                          new { idorigen=7, iddestino=1,tipo=9 },
                                                          new { idorigen=7, iddestino=2,tipo=9 },
                                                          new { idorigen=7, iddestino=3,tipo=9 },
                                                          new { idorigen=7, iddestino=4,tipo=9 },
                                                          new { idorigen=7, iddestino=5,tipo=9 },
                                                          new { idorigen=7, iddestino=6,tipo=9 },
                                                          new { idorigen=7, iddestino=7,tipo=9 },
                                                          new { idorigen=8, iddestino=1,tipo=9 },
                                                          new { idorigen=8, iddestino=2,tipo=9 },
                                                          new { idorigen=8, iddestino=3,tipo=9 },
                                                          new { idorigen=8, iddestino=4,tipo=9 },
                                                          new { idorigen=8, iddestino=5,tipo=9 },
                                                          new { idorigen=8, iddestino=6,tipo=9 },
                                                          new { idorigen=8, iddestino=7,tipo=9 },
                                                          new { idorigen=9, iddestino=1,tipo=9 },
                                                          new { idorigen=9, iddestino=2,tipo=9 },
                                                          new { idorigen=9, iddestino=3,tipo=9 },
                                                          new { idorigen=9, iddestino=4,tipo=9 },
                                                          new { idorigen=9, iddestino=5,tipo=9 },
                                                          new { idorigen=9, iddestino=6,tipo=9 },
                                                          new { idorigen=9, iddestino=7,tipo=9 },
                                                          new { idorigen=1, iddestino=0,tipo=5 },
                                                          new { idorigen=2, iddestino=0,tipo=5 },
                                                          new { idorigen=3, iddestino=0,tipo=5 },
                                                          new { idorigen=4, iddestino=1,tipo=5 },
                                                          new { idorigen=5, iddestino=0,tipo=5 },
                                                          new { idorigen=6, iddestino=0,tipo=5 },
                                                          new { idorigen=7, iddestino=1,tipo=5 },
                                                          new { idorigen=8, iddestino=0,tipo=5 },
                                                          new { idorigen=9, iddestino=1,tipo=5 },
                                                          new { idorigen=10, iddestino=0,tipo=5 },

                                                          
                                                          new { idorigen=1, iddestino=1,tipo=10 },
                                                          new { idorigen=2, iddestino=0,tipo=10 },
                                                          new { idorigen=3, iddestino=1,tipo=10 },
                                                          new { idorigen=1, iddestino=1,tipo=11 },
                                                          new { idorigen=2, iddestino=1,tipo=11 },
                                                          new { idorigen=3, iddestino=0,tipo=11 },
                                                          new { idorigen=4, iddestino=1,tipo=11 },
                                                          new { idorigen=5, iddestino=1,tipo=11 },
                                                          new { idorigen=6, iddestino=0,tipo=11 },
                                                          new { idorigen=7, iddestino=0,tipo=11 },
                                                          new { idorigen=8, iddestino=0,tipo=11 },
                                                          new { idorigen=9, iddestino=0,tipo=11 },
                                                          new { idorigen=1, iddestino=0,tipo=12 },
                                                          new { idorigen=2, iddestino=1,tipo=12 },
                                                          new { idorigen=3, iddestino=1,tipo=12 },
                                                          new { idorigen=4, iddestino=1,tipo=12 },
                                                          new { idorigen=5, iddestino=1,tipo=12 },
                                                          new { idorigen=6, iddestino=1,tipo=12 },
                                                          new { idorigen=1, iddestino=1,tipo=13 },
                                                          new { idorigen=1, iddestino=2,tipo=13 },
                                                          new { idorigen=1, iddestino=3,tipo=13 },
                                                          new { idorigen=2, iddestino=1,tipo=13 },
                                                          new { idorigen=2, iddestino=2,tipo=13 },
                                                          new { idorigen=2, iddestino=3,tipo=13 },
                                                          new { idorigen=3, iddestino=1,tipo=13 },
                                                          new { idorigen=3, iddestino=3,tipo=13 },
                                                          new { idorigen=4, iddestino=1,tipo=13 },
                                                          new { idorigen=4, iddestino=2,tipo=13 },
                                                          new { idorigen=4, iddestino=3,tipo=13 },
                                                          new { idorigen=5, iddestino=1,tipo=13 },
                                                          new { idorigen=5, iddestino=2,tipo=13 },
                                                          new { idorigen=5, iddestino=3,tipo=13 },
                                                          new { idorigen=6, iddestino=1,tipo=13 },
                                                          new { idorigen=6, iddestino=3,tipo=13 },
                                                          new { idorigen=7, iddestino=1,tipo=13 },
                                                          new { idorigen=7, iddestino=2,tipo=13 },
                                                          new { idorigen=7, iddestino=3,tipo=13 },
                                                          new { idorigen=8, iddestino=1,tipo=13 },
                                                          new { idorigen=8, iddestino=2,tipo=13 },
                                                          new { idorigen=8, iddestino=3,tipo=13 },
                                                          new { idorigen=9, iddestino=1,tipo=13 },
                                                          new { idorigen=9, iddestino=2,tipo=13 },
                                                          new { idorigen=9, iddestino=3,tipo=13 },
                                                          new { idorigen=1, iddestino=1,tipo=14 },
                                                          new { idorigen=2, iddestino=0,tipo=14 },
                                                          new { idorigen=3, iddestino=1,tipo=14 },
                                                          new { idorigen=4, iddestino=1,tipo=14 },
                                                          new { idorigen=1, iddestino=1,tipo=15 },
                                                          new { idorigen=2, iddestino=1,tipo=15 },
                                                          new { idorigen=3, iddestino=0,tipo=15 },
                                                          new { idorigen=4, iddestino=0,tipo=15 },
                                                          new { idorigen=1, iddestino=0,tipo=16 },
                                                          new { idorigen=2, iddestino=0,tipo=16 },
                                                          new { idorigen=3, iddestino=1,tipo=16 },
                                                          new { idorigen=4, iddestino=1,tipo=16 },
                                                          new { idorigen=1, iddestino=0,tipo=17 },
                                                          new { idorigen=2, iddestino=0,tipo=17 },
                                                          new { idorigen=3, iddestino=0,tipo=17 },
                                                          new { idorigen=4, iddestino=1,tipo=17 },
                                                          new { idorigen=5, iddestino=0,tipo=17 },
                                                          new { idorigen=6, iddestino=0,tipo=17 },
                                                          new { idorigen=7, iddestino=1,tipo=17 },
                                                          new { idorigen=8, iddestino=1,tipo=17 },
                                                          new { idorigen=9, iddestino=1,tipo=17 },
                                                          new { idorigen=1, iddestino=0,tipo=18 },
                                                          new { idorigen=2, iddestino=1,tipo=18 },
                                                          new { idorigen=3, iddestino=1,tipo=18 },
                                                          new { idorigen=4, iddestino=1,tipo=18 },
                                                          new { idorigen=5, iddestino=1,tipo=18 },
                                                          new { idorigen=6, iddestino=1,tipo=18 },
                                                          new { idorigen=7, iddestino=1,tipo=18 },
                                                          new { idorigen=8, iddestino=1,tipo=18 },
                                                          new { idorigen=9, iddestino=1,tipo=18 },
                                                          new { idorigen=1, iddestino=1,tipo=19 },
                                                          new { idorigen=2, iddestino=1,tipo=19 },
                                                          new { idorigen=3, iddestino=0,tipo=19 },
                                                          new { idorigen=4, iddestino=1,tipo=19 },
                                                          new { idorigen=5, iddestino=1,tipo=19 },
                                                          new { idorigen=0, iddestino=0,tipo=20 },
                                                          new { idorigen=1, iddestino=1,tipo=20 },
                                                          new { idorigen=2, iddestino=1,tipo=20 },
                                                          new { idorigen=3, iddestino=1,tipo=20 },
                                                          new { idorigen=4, iddestino=1,tipo=20 },
                                                          new { idorigen=5, iddestino=1,tipo=20 },
                                                          new { idorigen=6, iddestino=0,tipo=20 },
                                                          new { idorigen=7, iddestino=1,tipo=20 },
                                                          new { idorigen=8, iddestino=1,tipo=20 },
                                                          new { idorigen=9, iddestino=1,tipo=20 },
            };

        }
        protected void Application_PostAuthorizeRequest()
        {
            HttpContext.Current.SetSessionStateBehavior(SessionStateBehavior.Required);
        }
    }
}
